name: verify

on:
  push:
    branches: main

jobs:
   
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: "html"
            file: "index.html"
          - target: "pdf"
            file: "resume.pdf"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: "Install pandoc"
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.0.1/pandoc-3.0.1-1-amd64.deb
          sudo apt install ./pandoc-3.0.1-1-amd64.deb
      - name: "Install weasyprint"
        if: ${{ matrix.target }} == "pdf"
        run: |
          sudo apt install weasyprint
      - name: Run Verification
        run: bash verify.sh ${{ matrix.file }}
