name: verify

on:
  push:
    branches: main

jobs:
   
  build-and-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: "Install pandoc"
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.4/pandoc-3.4-1-amd64.deb
          sudo apt install ./pandoc-3.4-1-amd64.deb
      - name: "Install weasyprint and comparepdf"
        if: ${{ matrix.target }} == "pdf"
        run: |
          sudo apt install weasyprint comparepdf
      - name: Rebuild
        run: |
          cp resume.pdf resume-old.pdf
          bash build.sh html pdf
      - name: Run Verification
        run: |
          bash verify.sh index.html
          comparepdf -ct -v=1 resume.pdf resume-old.pdf

